method: method2_topk_kd

student_model_name: meta-llama/Llama-3.2-3B
teacher_model_name: meta-llama/Llama-3.1-8B

output_dir: outputs/method2_topk_kd_answer
seed: 42
max_length: 512

batch_size: 1
eval_batch_size: 1
gradient_accumulation_steps: 8
num_workers: 2

lr: 1.5e-5
weight_decay: 0.01
warmup_ratio: 0.05
max_grad_norm: 1.0

max_steps: 1500
val_ratio: 0.05

log_every: 10
eval_every: 100
save_every: 250

top_k: 64
kd_temperature: 2.0
kd_alpha: 0.3
kd_on_final_answer_only: true

eval_max_new_tokens: 192
eval_do_sample: false
eval_temperature: 1.0
eval_top_p: 1.0
eval_test_limit: null
